Additional Turris polishing
Addressing various small issues incompatible with Turris SW policies.

diff --git a/init/morce b/init/morce
--- a/init/morce
+++ b/init/morce
@@ -10,12 +10,13 @@ if [ -z "$(type -t extra_command)" ]; then
     EXTRA_COMMANDS="update_rules aggregate"
 else
     extra_command "update_rules" "Fetch new rules from Emerging threads"
-    extra_command "aggregate" "Aggregate alerts stored in database"
+    extra_command "aggregate"    "Aggregate alerts stored in database"
 fi
 
 config_load morce
 config_get ALERTS_DB setup live_database "/var/run/morce/morce-alerts.sqlite"
 config_get COLD_DB   setup cold_database "/srv/morce-alerts.sqlite"
+config_get IFACE     setup interface     "br-lan"
 RULES_DIR="/var/lib/morce-rules"
 
 # Rulesets we pull from Emerging Threads
@@ -38,27 +39,32 @@ die() {
     return 1
 }
 
-update_rules() {
+update_rules() (
+    local do_restart="yes"
+    [ "$1" != "no-restart" ] || do_restart=""
+
     mkdir -p "$RULES_DIR"
     [ -d "$RULES_DIR" -a -O "$RULES_DIR" -a -G "$RULES_DIR" ] || die "Can't create a rules directory"
     cd "$RULES_DIR"
 
     # Check for updated Emerging Threads rules
     local old_version="$(cat et-version.txt 2> /dev/null)"
+    local old_ruleset="$(cat et-ruleset.txt 2> /dev/null)"
     wget -O et-version.txt https://rules.emergingthreats.net/open/snort-2.9.0/version.txt || die "Can't get version of ET rules"
-    if [ "$old_version" != "$(cat et-version.txt)" ]; then
+    if [ "$old_version" != "$(cat et-version.txt)" ] || [ "$old_ruleset" != "$ET_RULES" ]; then
         for ruleset in $ET_RULES; do
             wget -O "emerging-${ruleset}.v2.rules" "https://rules.emergingthreats.net/open/snort-2.9.0/rules/emerging-${ruleset}.rules" || \
                 die "Can't download 'emerging-${ruleset}.rules' ruleset!"
             snort2lua -c "emerging-${ruleset}.v2.rules" -r "emerging-${ruleset}.v3.rules"
             # Drop comments and disabled rules to reduce size
             sed -i '/^#/ d' "emerging-${ruleset}.v3.rules"
-            # Make sure we have some rules after conversion
+            # Warn if we have almost no rules after conversion
             [ -n "$(head -n 10 "emerging-${ruleset}.v3.rules")" ] || echo "Converted rules from ${ruleset} are almost empty" >&2
             rm "emerging-${ruleset}.v2.rules"
             cat "emerging-${ruleset}.v3.rules"
             rm "emerging-${ruleset}.v3.rules"
         done > emerging-all.rules
+        echo "$ET_RULES" > et-ruleset.txt
     fi
     [ -n "$(head -n 10 "emerging-all.rules")" ] || die "Downloaded emerging ruleset is empty"
 
@@ -69,7 +75,7 @@ update_rules() {
         || die "Can't get Snort rules version"
     if [ "$old_version" != "$(cat talos-version.txt)" ]; then
         wget -O - https://www.snort.org/downloads/community/snort3-community-rules.tar.gz \
-            | tar -xczf - snort3-community-rules/snort3-community.rules \
+            | tar -xOzf - snort3-community-rules/snort3-community.rules \
             | grep -v '^#' > snort3-community.rules || die "Can't download Snort ruleset"
     fi
 
@@ -86,12 +92,11 @@ suppress = {
 EOF
 
     # Restart service if appropriate
-    local old_version="$(cat version.txt)"
+    local old_version="$(cat version.txt 2> /dev/null)"
     cat morce_rules.lua et-version.txt talos-version.txt | sha256sum > version.txt
     [ "$old_version" != "$(cat version.txt)" ] || return 0
-    [ "$1" == "no-restart" ] && return 0
-    procd_send_signal morce '*' SIGHUP
-}
+    [ -z "$do_restart" ] || procd_send_signal morce '*' SIGHUP
+)
 
 aggregate() {
     [ -f "$ALERTS_DB" ] || return 0
@@ -109,12 +114,16 @@ aggregate() {
 }
 
 start_service() {
-    [ "$1" = "no-update" ] || update_rules no-restart || return 1
+    # If running do not proceed with rules updates and DB copies just to fail later
+    if procd_running morce; then
+        return 0
+    fi
+    procd_open_instance
+    update_rules no-restart || return 1
     local alerts_db_dir="$(dirname "$ALERTS_DB")"
     mkdir -p "$alerts_db_dir"
     [ -d "$alerts_db_dir" -a -O "$alerts_db_dir" -a -G "$alerts_db_dir" ] || die "Can't create a directory for alerts database"
-    [ -r "$COLD_DB" -a "$ALERTS_DB" -nt "$COLD_DB" ] || cp "$COLD_DB" "$ALERTS_DB"
-    procd_open_instance
+    [ \! -r "$COLD_DB" ] || [ "$ALERTS_DB" -nt "$COLD_DB" ] || cp "$COLD_DB" "$ALERTS_DB"
     procd_set_param command /usr/bin/snort \
         --daq-dir /usr/lib/daq/ \
         --script-path /usr/share/morce/loggers/ \
@@ -122,16 +131,21 @@ start_service() {
         -c /etc/snort/snort.lua \
         --tweaks balanced \
         --lua "include '$RULES_DIR/morce_rules.lua'" \
-        -i "br-lan" \
+        -i "$IFACE" \
         -A alert_morce
     procd_set_param file "$RULES_DIR"/morce_rules.lua
     procd_set_param stderr 1
     procd_set_param stdout 1
-    procd_set_param reload_signal SIGHUP
+    procd_add_reload_trigger "morce"
     procd_set_param respawn
     procd_close_instance
 }
 
 service_stopped() {
     aggregate
+}
+
+reload_service() {
+    # The only thing that might require reload is changing the ruleset
+    update_rules
 }
